//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dil {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PETNET.Resources.HomeTexts", typeof(HomeTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMİN PANELİ.
        /// </summary>
        public static string adminpanel {
            get {
                return ResourceManager.GetString("adminpanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string altblog {
            get {
                return ResourceManager.GetString("altblog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sahiplendirme.
        /// </summary>
        public static string altsahiplendirme {
            get {
                return ResourceManager.GetString("altsahiplendirme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sahiplenme.
        /// </summary>
        public static string altsahiplenme {
            get {
                return ResourceManager.GetString("altsahiplenme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAĞIŞÇI OLMAK İSTER MİSİNİZ?.
        /// </summary>
        public static string bagis {
            get {
                return ResourceManager.GetString("bagis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAĞIŞ YAPMAK İSTER MİSİNİZ?.
        /// </summary>
        public static string bagismi {
            get {
                return ResourceManager.GetString("bagismi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAŞLIK.
        /// </summary>
        public static string baslik {
            get {
                return ResourceManager.GetString("baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string blogbuton {
            get {
                return ResourceManager.GetString("blogbuton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLOG BÖLÜMÜNDE YAZAR OLMAK İSTER MİSİNİZ ?.
        /// </summary>
        public static string blogistermi {
            get {
                return ResourceManager.GetString("blogistermi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLOGLAR.
        /// </summary>
        public static string bloglar {
            get {
                return ResourceManager.GetString("bloglar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PETNET kullanıcıları deneyimlerini bloglar aracılığıyla paylaşabiliriler!.
        /// </summary>
        public static string blogmetin {
            get {
                return ResourceManager.GetString("blogmetin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAKARYA ÜNİVERSİTESİ BİLGİSAYAR MÜHENDİSLİĞİ.
        /// </summary>
        public static string bolum {
            get {
                return ResourceManager.GetString("bolum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÇIKIŞ.
        /// </summary>
        public static string cikis {
            get {
                return ResourceManager.GetString("cikis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinsi.
        /// </summary>
        public static string cinsi {
            get {
                return ResourceManager.GetString("cinsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinsiyeti.
        /// </summary>
        public static string cinsiyeti {
            get {
                return ResourceManager.GetString("cinsiyeti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DETAYLAR.
        /// </summary>
        public static string detaylar {
            get {
                return ResourceManager.GetString("detaylar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Seçilmedi.
        /// </summary>
        public static string dosyayok {
            get {
                return ResourceManager.GetString("dosyayok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DÜZENLE.
        /// </summary>
        public static string duzenle {
            get {
                return ResourceManager.GetString("duzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DÜZENLENECEK BLOG.
        /// </summary>
        public static string duzenlenecekblog {
            get {
                return ResourceManager.GetString("duzenlenecekblog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EKLE.
        /// </summary>
        public static string ekle {
            get {
                return ResourceManager.GetString("ekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EKLENECEK BLOG.
        /// </summary>
        public static string eklenecekblog {
            get {
                return ResourceManager.GetString("eklenecekblog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EKLEYEN KULLANICI.
        /// </summary>
        public static string ekleyenkullanici {
            get {
                return ResourceManager.GetString("ekleyenkullanici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESKİ FOTOĞRAF.
        /// </summary>
        public static string eskifotograf {
            get {
                return ResourceManager.GetString("eskifotograf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORUM.
        /// </summary>
        public static string forum {
            get {
                return ResourceManager.GetString("forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forumlar.
        /// </summary>
        public static string forumlar {
            get {
                return ResourceManager.GetString("forumlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOTOĞRAF.
        /// </summary>
        public static string fotograf {
            get {
                return ResourceManager.GetString("fotograf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri.
        /// </summary>
        public static string geri {
            get {
                return ResourceManager.GetString("geri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GİRİŞ.
        /// </summary>
        public static string girisbuton {
            get {
                return ResourceManager.GetString("girisbuton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GİRİŞ YAP.
        /// </summary>
        public static string girisyap {
            get {
                return ResourceManager.GetString("girisyap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GÜNCELLE.
        /// </summary>
        public static string guncelle {
            get {
                return ResourceManager.GetString("guncelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAYVAN HAKLARI HAKKINDA.
        /// </summary>
        public static string haklar {
            get {
                return ResourceManager.GetString("haklar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hayvan hakları, hayvanların insancıl muamele görmelerini sağlayan haklardır. Bütün hayvanlar yaşam önünde eşit doğarlar ve aynı varolma hakkında sahiptirler. Bütün hayvanlar saygı görme hakkında sahiptir. Bir insan öbür hayvanları yok edemez. Bütün hayvanların insanca gözetilme, bakılma ve korunma hakları vardır. Hiçbir hayvana kötü davranılamaz, acımasız ve zalimce eylem yapılamaz. Geleneksel olarak insanların çevresinde yaşayan bir türden olan bütün hayvanlar uyumlu bir biçimde türüne özgü yaşam koşulları [rest of string was truncated]&quot;;.
        /// </summary>
        public static string haklartext {
            get {
                return ResourceManager.GetString("haklartext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İÇERİK.
        /// </summary>
        public static string icerik {
            get {
                return ResourceManager.GetString("icerik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İLETİŞİM.
        /// </summary>
        public static string iletisim {
            get {
                return ResourceManager.GetString("iletisim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İLETİŞİM BİLGİLERİ.
        /// </summary>
        public static string iletisimbilgi {
            get {
                return ResourceManager.GetString("iletisimbilgi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İSİM-SOYİSİM.
        /// </summary>
        public static string isimsoyad {
            get {
                return ResourceManager.GetString("isimsoyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsmi.
        /// </summary>
        public static string ismi {
            get {
                return ResourceManager.GetString("ismi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoriler.
        /// </summary>
        public static string kategoriler {
            get {
                return ResourceManager.GetString("kategoriler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAYDET.
        /// </summary>
        public static string kaydet {
            get {
                return ResourceManager.GetString("kaydet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAYDOL.
        /// </summary>
        public static string kaydol {
            get {
                return ResourceManager.GetString("kaydol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAYIT OL.
        /// </summary>
        public static string kayitol {
            get {
                return ResourceManager.GetString("kayitol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KULLANICI ADI.
        /// </summary>
        public static string kullaniciadi {
            get {
                return ResourceManager.GetString("kullaniciadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PETNET Nedir?.
        /// </summary>
        public static string nedir {
            get {
                return ResourceManager.GetString("nedir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PETNET ücretsiz bir evcil hayvan sahiplenme ve sahiplendirme platformudur. Bunların yanında, hayvanların çıkarlarını gözeten sosyal yardım kuruluşlarına bağış yapabilir, birbirinden farklı blog yazılarını okuyabilir ve kendi bloğunuzu oluşturabilirsiniz..
        /// </summary>
        public static string nedirmetin {
            get {
                return ResourceManager.GetString("nedirmetin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PETNET.
        /// </summary>
        public static string petnet {
            get {
                return ResourceManager.GetString("petnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PETNET ADMİNİ.
        /// </summary>
        public static string petnetadmini {
            get {
                return ResourceManager.GetString("petnetadmini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROFİL.
        /// </summary>
        public static string profil {
            get {
                return ResourceManager.GetString("profil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROL.
        /// </summary>
        public static string rol {
            get {
                return ResourceManager.GetString("rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAHİBİ.
        /// </summary>
        public static string sahibi {
            get {
                return ResourceManager.GetString("sahibi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAHİPLENDİRME FORMU.
        /// </summary>
        public static string sahipform {
            get {
                return ResourceManager.GetString("sahipform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAHİPLENİLECEK HAYVAN.
        /// </summary>
        public static string sahiphayvan {
            get {
                return ResourceManager.GetString("sahiphayvan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sahiplenmek İçin.
        /// </summary>
        public static string sahipicin {
            get {
                return ResourceManager.GetString("sahipicin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sahiplen!.
        /// </summary>
        public static string sahiplenbuton {
            get {
                return ResourceManager.GetString("sahiplenbuton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sahiplendir!.
        /// </summary>
        public static string sahiplendirbuton {
            get {
                return ResourceManager.GetString("sahiplendirbuton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sahiplendirilecekler.
        /// </summary>
        public static string sahiplendirelecek {
            get {
                return ResourceManager.GetString("sahiplendirelecek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAHİPLENDİRME.
        /// </summary>
        public static string sahiplendirme {
            get {
                return ResourceManager.GetString("sahiplendirme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Büyük heveslerle alınan ancak bakılamadığı için terk edilen evcil hayvanlar, yetiştirildiği ortama yani bir yuvaya ihtiyaç duyar. Evcil hayvanınızı sokağa terk etmek yerine ona yeni bir yuva bulmalısınız!.
        /// </summary>
        public static string sahiplendirmetin {
            get {
                return ResourceManager.GetString("sahiplendirmetin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAHİPLENME.
        /// </summary>
        public static string sahiplenme {
            get {
                return ResourceManager.GetString("sahiplenme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sahiplendriilmek üzere bekleyen evcil hayvanları buradan görüntüleyebilir, sahiplenmek istediğiniz durumda iletişime geçebilirsiniz!.
        /// </summary>
        public static string sahiplenmetin {
            get {
                return ResourceManager.GetString("sahiplenmetin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ŞEHİR.
        /// </summary>
        public static string sehir {
            get {
                return ResourceManager.GetString("sehir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ŞİFRE.
        /// </summary>
        public static string sifre {
            get {
                return ResourceManager.GetString("sifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SİL.
        /// </summary>
        public static string sil {
            get {
                return ResourceManager.GetString("sil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SİLMEK ÜZERESİNİZ, SİLMEK İSTEDİĞİNİZE EMİN MİSİNİZ?.
        /// </summary>
        public static string siluyar {
            get {
                return ResourceManager.GetString("siluyar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.SINIF.
        /// </summary>
        public static string sinif {
            get {
                return ResourceManager.GetString("sinif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAKIMIMIZ.
        /// </summary>
        public static string takimimiz {
            get {
                return ResourceManager.GetString("takimimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TARİH.
        /// </summary>
        public static string tarih {
            get {
                return ResourceManager.GetString("tarih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türü.
        /// </summary>
        public static string turu {
            get {
                return ResourceManager.GetString("turu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TÜRKİYE.
        /// </summary>
        public static string ulke {
            get {
                return ResourceManager.GetString("ulke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÜYE.
        /// </summary>
        public static string uye {
            get {
                return ResourceManager.GetString("uye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÜYE GİRİŞ.
        /// </summary>
        public static string uyegiris {
            get {
                return ResourceManager.GetString("uyegiris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üyeler.
        /// </summary>
        public static string uyeler {
            get {
                return ResourceManager.GetString("uyeler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yayınlayan.
        /// </summary>
        public static string yayinlayan {
            get {
                return ResourceManager.GetString("yayinlayan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YENİ ÜYE.
        /// </summary>
        public static string yeniuye {
            get {
                return ResourceManager.GetString("yeniuye", resourceCulture);
            }
        }
    }
}
